spring:
  application:
    name: transcriber-api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080
  servlet:
    context-path: /transcriber-api

inventory:
  url: toto